"""Add password reset request check field

Revision ID: 19fe84c3e51d
Revises: 2c4c24c026a3
Create Date: 2023-09-12 10:01:48.016946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fe84c3e51d'
down_revision = '2c4c24c026a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_password_reset_token', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_password_reset_token')

    # ### end Alembic commands ###
