"""Fix boolean data type in is_public post attribute

Revision ID: 2c4c24c026a3
Revises: 0d9d96015f93
Create Date: 2023-09-06 23:40:30.406817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c4c24c026a3'
down_revision = '0d9d96015f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
